language: python
cache: pip
python:
# temporarily disabled due to broken pysmi dependency
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "nightly"
#  - "pypy"
#  - "pypy3"
install:
  - pip install -r requirements.txt -r devel-requirements.txt
  - pip install -e .
script:
  - sh runtests.sh
